Project03/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VideoController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\VolunteerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\BlogCategoryController;
use App\Http\Controllers\DownloadFileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function(){
    return redirect('login');
});

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');
Route::post('logout', [AuthController::class, 'destroy'])->name('logout');



Route::middleware('admin')->group(function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::get('applications/active', [ApplicationController::class, 'active']);
    Route::get('applications/archived', [ApplicationController::class, 'archived']);
    Route::get('applications/archivedApplications', [ApplicationController::class, 'archivedApplications'])->name('applications.archivedApplications');
    Route::resource('applications', ApplicationController::class);
    Route::get('applications/{application}/makeDonation/{id}', [ApplicationController::class, 'makeDonation']);


    Route::get('contacts/active', [ContactController::class, 'active']);
    Route::get('contacts/archived', [ContactController::class, 'archived']);
    Route::get('contacts/archivedContacts', [ContactController::class, 'archivedContacts'])->name('contacts.archivedContacts');
    Route::resource('contacts', ContactController::class);

    Route::get('volunteers/requests', [VolunteerController::class, 'requests']);
    Route::get('volunteers/volunteers', [VolunteerController::class, 'volunteers']);
    Route::get('volunteers/activeVolunteers', [VolunteerController::class, 'activeVolunteers'])->name('volunteers.activeVolunteers');
    Route::resource('volunteers', VolunteerController::class);

    Route::get('donations/allDonations', [DonationController::class, 'allDonations']);
    Route::resource('donations', DonationController::class);

    Route::resource('partners', PartnerController::class);

    Route::resource('blogCategories', BlogCategoryController::class);

    Route::resource('blogs', BlogController::class);

    Route::resource('videos', VideoController::class);

    Route::get('storage/{file_path}')->name('downloadFile');
});

Project03/app/Models/Partner.php
<?php

namespace App\Models;

use App\Models\PartnerType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Partner extends Model
{
    use HasFactory;

    public function partnerType()
    {
        return $this->hasOne(PartnerType::class);
    }
}

Project03/app/Models/PartnerType.php
<?php

namespace App\Models;

use App\Models\Partner;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class PartnerType extends Model
{
    use HasFactory;

    public function partners()
    {
        return $this->belongsToMany(Partner::class);
    }
}

Project03/app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Partner;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\StorePartnerRequest;
use App\Http\Requests\UpdatePartnerRequest;
use App\Models\PartnerType;

class PartnerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $partners = Partner::get();

        $partnerTypes = PartnerType::get();

        return view('partners.index', compact('partners'), compact('partnerTypes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $partnerTypes = PartnerType::get();

        return view('partners.create', compact('partnerTypes'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePartnerRequest $request)
    {
        $partner = new Partner();
        $partner->name = $request->name;
        $partner->partner_url = $request->partner_url;
        $partner->partner_type_id = $request->partner_type_id;
        
        $image = $request->file('image');
        $fileName = md5($image->getClientOriginalName().time()) . '.' . $image->getClientOriginalExtension();
        $filePath = 'uploads/'.$fileName;
        Storage::disk('public')->put($filePath, file_get_contents($request->file('image')));
        $partner->image = $filePath;
        
        if($partner->save()) {
            return redirect()->route('partners.index')->with('success', 'Partner added successfully!');
        } else {
            return redirect()->route('partners.index')->with('error', 'Something went wrong...');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Partner $partner)
    {
        $partnerType = PartnerType::where('id', $partner->partner_type_id)->get();
        $partnerType = $partnerType[0]->partner_type;

        return view('partners.show', compact('partner'), compact('partnerType'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Partner $partner)
    {
        $partnerTypes = PartnerType::get();

        return view('partners.edit', compact('partner'), compact('partnerTypes'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdatePartnerRequest $request, Partner $partner)
    {
        $partner->name = $request->name;
        $partner->partner_url = $request->partner_url;
        $partner->partner_type_id = $request->partner_type_id;

        if ($request->file('image')) {
            $image = $request->file('image');
            $fileName = md5($image->getClientOriginalName().time()) . '.' . $image->getClientOriginalExtension();
            $filePath = 'uploads/'.$fileName;
            Storage::disk('public')->put($filePath, file_get_contents($request->file('image')));
            $partner->image = $filePath;
        } 
        
        if($partner->save()) {
            return redirect()->route('partners.index')->with('success', 'Partner updated successfully!');
        } else {
            return redirect()->route('partners.index')->with('error', 'Something went wrong...');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Partner $partner)
    {
        if($partner->delete()) {
            return redirect()->route('partners.index')->with('success', 'Partner deleted successfully!');
        } else {
        return redirect()->route('partners.index')->with('error', 'Something went wrong...');
        }
    }
}

Project03/resources/views/partners/create.blade.php
@extends('layouts.app')

@section('content')


<div class="flex flex-row justify-center grow bg-gray-50">
    <div class="basis-2/3 text-center">
    <h1 class="mt-10 mb-2 text-2xl text-black">Create partner</h1>

        <div class="md:w-2/3 lg:w-2/4 mx-auto text-left bg-gray-50 p-8 border rounded-lg">
            <form class="my-5" action="{{ route('partners.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="mb-6">
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name:</label>
                    <input type="text" id="name" name="name" value="{{old('name')}}" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('name') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter partner name here">
                    @error('name')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                    @enderror
                </div>

                <div class="mb-6">
                    <label for="partner_url" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Web page:</label>
                    <input type="text" id="partner_url" name="partner_url" value="{{old('partner_url')}}" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('partner_url') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter URL here">
                    @error('partner_url')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                    @enderror
                </div>

                <div class="mb-6">
                    <label for="partner_type_id" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Type</label>
                    <select id="partner_type_id" name="partner_type_id" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('partner_type_id') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror">
                        <option value="-1">Select partner ...</option>
                        @foreach ($partnerTypes as $partner)
                        <option value="{{$partner->id}}" @if(old('partner_type_id') > 0 && old('partner_type_id')==$partner->id) selected @endif>{{$partner->partner_type}}</option>
                        @endforeach
                    </select>
                    @error('partner_type_id')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500"> {{ $message }}</p>
                    @enderror
                </div>
                
                <div class="mb-6">
                    <label for="image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Image:</label>
                    <input type="file" name="image" id="image" class="text-sm @error('image') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror rounded w-full">
                    @error('image')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500"> {{ $message }}</p>
                    @enderror
                </div>
                <div class="flex justify-between">
                    <a type="button" href="{{ url()->previous() }}" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>

                    <button type="submit" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-lime-600 hover:bg-lime-500 text-gray-100 rounded-lg focus:border-4 border-green-300 my-5 ml-auto mr-0">Create</button>
                </div>
            </form>
        </div>

    </div>

</div>


@endsection

Project03/resources/views/partners/edit.blade.php
@extends('layouts.app')

@section('content')


<div class="flex flex-row justify-center grow bg-gray-50">
    <div class="basis-2/3 text-center">
    <h1 class="mt-10 mb-2 text-2xl text-black">Edit partner</h1>

        <div class="md:w-2/3 lg:w-2/4 mx-auto text-left bg-gray-50 p-8 border rounded-lg">
            <form class="my-5" action="{{ route('partners.update', $partner) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="mb-6">
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name:</label>
                    <input type="text" id="name" name="name" value="{{old('name', $partner->name)}}" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('name') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter partner name here">
                    @error('name')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                    @enderror
                </div>

                <div class="mb-6">
                    <label for="partner_url" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Web page:</label>
                    <input type="text" id="partner_url" name="partner_url" value="{{old('partner_url', $partner->partner_url)}}" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('partner_url') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter URL here">
                    @error('partner_url')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                    @enderror
                </div>

                <div class="mb-6">
                    <label for="partner_type_id" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Type</label>
                    <select id="partner_type_id" name="partner_type_id" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('partner_type_id') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror">
                        <option value="-1">Select partner ...</option>
                        @foreach ($partnerTypes as $partner)
                        <option value="{{$partner->id}}" @if(old('partner_type_id', $partner->id) > 0 && old('partner_type_id', $partner->id)==$partner->id) selected @endif>{{$partner->partner_type}}</option>
                        @endforeach
                    </select>
                    @error('partner_type_id')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500"> {{ $message }}</p>
                    @enderror
                </div>
                
                <div class="mb-6">
                    <label for="image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Image:</label>
                    <input type="file" name="image" id="image" class="text-sm @error('image') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror rounded w-full">
                    @error('image')
                    <p class="mt-2 text-sm text-red-600 dark:text-red-500"> {{ $message }}</p>
                    @enderror
                </div>
                <div class="flex justify-between">
                    <a type="button" href="{{ url()->previous() }}" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>

                    <button type="submit" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-lime-600 hover:bg-lime-500 text-gray-100 rounded-lg focus:border-4 border-green-300 my-5 ml-auto mr-0">Update</button>
                </div>
            </form>
        </div>

    </div>

</div>


@endsection

Project03/resources/views/partners/index.blade.php
@extends('layouts.app')

@section('content')
<div class="flex flex-row justify-center grow bg-gray-50">
        <div class="basis-2/3 text-center">
            <h1 class="mt-10 text-2xl text-black">Partners</h1>

            <div class="text-start">
                <a type="button" href="{{ route('partners.create')}}" class="text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-small rounded-lg text-sm px-5 py-1.5 text-center dark:bg-red-700 dark:hover:bg-red-800 dark:focus:ring-red-800 mb-6 mx-auto">Add new partner</a>
            </div>

            <div class="grid grid-cols-2 md:grid-cols-3 gap-4 lg:gap-6">
            @foreach($partners as $partner)
                <div class="flex flex-col shadow-lg mx-auto my-5 border rounded-lg w-full motion-safe:hover:scale-[1.05] transition-all duration-250 bg-gray-50 p-2 overflow-hidden">
                    <div class="w-full bg-gray-50">
                    <a href="{{ route('partners.show', $partner)}}" class="w-full"><img class="object-cover w-full rounded-t-lg p-5" src="{{ asset('storage/'.$partner->image) }}" alt=""></a>
                    </div>
                    <div class="flex flex-col p-4 leading-normal text-start w-full bg-gray-50">
                        <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white"><a href="{{ route('partners.show', $partner)}}">{{ $partner->name}}</a></h5>
                        <p class="mb-3 text-xs text-gray-700 dark:text-gray-400">partner URL: <br><a href="{{ $partner->partner_url}}" class="text-indigo-700 dark:text-indigo-400 hover:border-b hover:border-indigo-700">{{ $partner->partner_url}}</a></p>
                    </div>

                </div>

            @endforeach
            </div>
        </div>

    </div>
@endsection

Project03/resources/views/partners/show.blade.php
@extends('layouts.app')

@section('content')

<div class="flex flex-row justify-center pb-10 grow bg-gray-50">
    <div class="basis-2/3 text-left">

        <div class="flex flex-row justify-around">
            <div class="text-start">
                <a type="button" href="{{ route('partners.index') }}" class="w-32 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>
            </div>
            <div class="text-start">
                <a type="button" href="{{ route('partners.edit', $partner)}}" class="w-32 text-center text-sm p-1.5 pl-5 pr-5 transition-colors duration-700 transform bg-amber-600 hover:bg-amber-500 text-gray-100 rounded-lg focus:border-4 border-amber-300 mt-5 ml-0 mr-auto">Edit</a>
            </div>
            <div class="text-start">
                <button type="button" class="w-32 text-center text-sm p-1.5 pl-5 pr-5 transition-colors duration-700 transform bg-rose-700/90 hover:bg-rose-500 text-gray-100 rounded-lg focus:border-4 border-rose-300 mt-5 ml-0 mr-auto" data-modal-target="delete-popup-modal" data-modal-toggle="delete-popup-modal">Delete</button>
            </div>
        </div>

        <div class="flex flex-col mx-auto my-5 border rounded-lg w-full shadow-lg bg-gray-50 p-2 overflow-hidden overflow-y-auto">
            <div class="bg-gray-50 w-60 mx-auto">
                <img class="object-cover w-full md:rounded-lg" src="{{ asset('storage/'.$partner->image) }}" alt="">
            </div>
            <div class="flex flex-col p-4 leading-normal text-center w-full bg-gray-50">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">{{ $partner->name}}</h5>
                <p class="mb-3 text-sm text-gray-700 dark:text-gray-400">Partner type: <br>{{ $partnerType }}</p>
                <p class="mb-3 text-sm text-gray-700 dark:text-gray-400">Partner URL: <br><a href="{{ $partner->partner_url}}" class="text-indigo-700 dark:text-indigo-400 hover:border-b hover:border-indigo-700">{{ $partner->partner_url}}</a></p>
            </div>
        </div>
    </div>

    <div id="delete-popup-modal" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] md:h-full">
        <div class="relative w-full h-full max-w-md md:h-auto">
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="delete-popup-modal">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
                <div class="p-6 text-center">
                    <svg aria-hidden="true" class="mx-auto mb-4 text-gray-400 w-14 h-14 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to delete this partner?</h3>
                    <div class="flex justify-around">
                        <form action="{{ route('partners.destroy', $partner)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" data-modal-hide="delete-popup-modal" type="button" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">
                                Yes, I'm sure
                            </button>
                        </form>
                        <button data-modal-hide="delete-popup-modal" type="button" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">No, cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
@endsection