Project03/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\VideoController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\VolunteerController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\BlogCategoryController;
use App\Http\Controllers\DownloadFileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function(){
    return redirect('login');
});

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');
Route::post('logout', [AuthController::class, 'destroy'])->name('logout');



Route::middleware('admin')->group(function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::get('applications/active', [ApplicationController::class, 'active']);
    Route::get('applications/archived', [ApplicationController::class, 'archived']);
    Route::get('applications/archivedApplications', [ApplicationController::class, 'archivedApplications'])->name('applications.archivedApplications');
    Route::resource('applications', ApplicationController::class);
    Route::get('applications/{application}/makeDonation/{id}', [ApplicationController::class, 'makeDonation']);


    Route::get('contacts/active', [ContactController::class, 'active']);
    Route::get('contacts/archived', [ContactController::class, 'archived']);
    Route::get('contacts/archivedContacts', [ContactController::class, 'archivedContacts'])->name('contacts.archivedContacts');
    Route::resource('contacts', ContactController::class);

    Route::get('volunteers/requests', [VolunteerController::class, 'requests']);
    Route::get('volunteers/volunteers', [VolunteerController::class, 'volunteers']);
    Route::get('volunteers/activeVolunteers', [VolunteerController::class, 'activeVolunteers'])->name('volunteers.activeVolunteers');
    Route::resource('volunteers', VolunteerController::class);

    Route::get('donations/allDonations', [DonationController::class, 'allDonations']);
    Route::resource('donations', DonationController::class);

    Route::resource('partners', PartnerController::class);

    Route::resource('blogCategories', BlogCategoryController::class);

    Route::resource('blogs', BlogController::class);

    Route::resource('videos', VideoController::class);

    Route::get('storage/{file_path}')->name('downloadFile');
});

Project03/app/Models/Donation.php
<?php

namespace App\Models;

use App\Models\Client;
use App\Models\Equipment;
use App\Models\Application;
use App\Models\EquipmentType;
use App\Models\ClientDonation;
use App\Models\DonationEquipment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Donation extends Model
{
    use HasFactory;

    public function application()
    {
        return $this->belongsTo(Application::class);
    }

    public function client()
    {
        return $this->belongsToMany(Client::class, 'client_donations',  'donation_id', 'client_id');
    }

    public function equipment()
    {
        return $this->belongsToMany(Equipment::class, 'donation_equipment', 'donation_id', 'equipment_id');
    }

    public function equipment_type()
    {
        return $this->belongsTo(EquipmentType::class);
    }

    public function client_donation()
    {
        return $this->hasOne(ClientDonation::class);
    }

    public function donation_equipment()
    {
        return $this->hasOne(DonationEquipment::class);
    }
}

Project03/app/Http/Controllers/DonationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\Donation;
use App\Models\Application;
use Illuminate\Http\Request;
use App\Models\ClientDonation;
use App\Models\ClientEquipment;
use App\Models\DonationEquipment;
use App\Models\ApplicationDonation;
use Yajra\DataTables\Facades\DataTables;
use App\Http\Requests\StoreDonationRequest;
use App\Http\Requests\UpdateDonationRequest;

class DonationController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('donations.index');
    }

    public function allDonations()
    {
        $donations = Donation::query()
        ->join('application_donations', 'application_donations.donation_id', '=', 'donations.id')
        ->join('client_donations', 'client_donations.donation_id', '=', 'donations.id')
        ->join('clients', 'clients.id', '=', 'client_donations.client_id')
        ->join('donation_equipment', 'donation_equipment.donation_id', '=', 'donations.id')
        ->join('equipment', 'equipment.id', '=', 'donation_equipment.equipment_id')
        ->select('donations.id AS donation_id', 'clients.first_name', 'clients.last_name', 'clients.city', 'clients.email', 'clients.phone_number', 'donations.id', 'donations.donation', 'donations.created_at AS donations_created_at');
        
        return DataTables::eloquent($donations)->toJson();
    }



    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreDonationRequest $request)
    {
        $donation = new Donation();
        $donation->donation = $request->donation;
        if (!$donation->save()) {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        } else {
            $donation->save();
        }
        
        $donationId = $donation->id;

        $application = Application::where('client_id', $request->client_id)->first();
        $applicationId = $application->id;

        $applicationDonation = new ApplicationDonation();
        $applicationDonation->application_id = $applicationId;
        $applicationDonation->donation_id = $donationId;
        if (!$applicationDonation->save()) {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        } else {
            $applicationDonation->save();
        }

        $application->application_status_id = 3;
        $application->save();
        
        $clientDonation = new ClientDonation();
        $clientDonation->client_id = $request->client_id;
        $clientDonation->donation_id = $donationId;
        if (!$clientDonation->save()) {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        } else {
            $clientDonation->save();
        }

        $clientEquipment = ClientEquipment::where('client_id', $request->client_id)->first();
        $equipmentId =  $clientEquipment->equipment_id;

        $donationEquipment = new DonationEquipment();
        $donationEquipment->donation_id = $donationId;
        $donationEquipment->equipment_id = $equipmentId;
        if ($donationEquipment->save()) {
            return redirect()->route('donations.index')->with('success', 'Donation added successfully!');
        } else {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $donation = Donation::where('id', $id)->first();

        return view('donations.show', compact('donation'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $donation = Donation::where('id', $id)->first();

        return view('donations.edit', compact('donation'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateDonationRequest $request, Donation $donation)
    {

        $donation = Donation::where('id', $donation->id)->first();
        $donation->donation = $request->donation;

        if ($donation->save()) {
            return redirect()->route('donations.index')->with('success', 'Donation updated successfully!');
        } else {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Donation $donation)
    {
        if ($donation->delete()) {
            return redirect()->route('donations.index')->with('success', 'Donation deleted successfully!');
        } else {
            return redirect()->route('donations.index')->with('error', 'Something went wrong...');
        }
    }

}

Project03/resources/views/donations/create.blade.php
@extends('layouts.app')

@section('content')

<div class="flex flex-row justify-center pb-10 grow bg-gray-50">
    <div class="basis-2/3 text-left">

        <div class="flex flex-row justify-around">
            <div class="text-start">
                <a type="button" href="{{ url()->previous() }}" class="w-32 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>
            </div>
        </div>

        <div class="flex flex-col mx-auto my-5 border rounded-lg w-full bg-gray-50 p-2 overflow-hidden overflow-y-auto p-6 shadow-lg lg:w-5/6">
            <div class="flex flex-row justify-around">
                <div class="text-end">
                    <a href="" type="button" id="donateBtn" data-id="{{ $client }}" class="w-32 text-green-600 hover:text-white border-2 border-green-600 bg-green-50 hover:bg-green-600 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-600">Donate!</a>
                </div>
            </div>
            <div class="flex justify-between">
                <div class="text-start">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-start">{{ $client->first_name . " " . $client->last_name }}</h6>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">City:</span> {{ $client->city }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Email:</span> {{ $client->email }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Phone number:</span> {{ $client->phone_number }}</p>
                </div>
                <div class="text-end">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-end">Опрема: {{ $client->equipment[0]->equipment_type }}</h6>
                </div>
            </div>
            <p class="font-normal text-gray-700 dark:text-gray-400 w-full mt-2"><span class="font-semibold">Donating: </span></p>
            <form id="donationForm" class="mb-5" action="{{ route('donations.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                @error('donation')
                <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                @enderror
                <input type="hidden" id="client_id" value="{{old('client_id', $client->id)}}" name="client_id">

                <label for="donation" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"></label>
                            <textarea rows="6" type="text" id="donation" name="donation" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('donation') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter donation here...">{{old('donation')}}</textarea>
                <button type="submit" id="donationFormBtn" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-lime-600 hover:bg-lime-500 text-gray-100 rounded-lg focus:border-4 border-green-300 my-5 ml-auto mr-0 hidden">Create</button>
            </form>
        </div>
    </div>

</div>
</div>

</div>
</div>
@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    $(function() {
        let donateBtn = $("#donateBtn");
        let donationFormBtn = $("#donationFormBtn");

        donateBtn.click( function() {
                donationFormBtn.click()
                return false;
            }
        )

    })
</script>

Project03/resources/views/donations/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="flex flex-row justify-center pb-10 grow bg-gray-50">
    <div class="basis-2/3 text-left">

        <div class="flex flex-row justify-around">
            <div class="text-start">
                <a type="button" href="{{ url()->previous() }}" class="w-32 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>
            </div>
        </div>
        <h6 class="text-2xl tracking-tight text-gray-900 dark:text-white text-center mb-2">Update donation:</h6>

        <div class="flex flex-col mx-auto mb-5 border rounded-lg w-full bg-gray-50 p-2 overflow-hidden overflow-y-auto p-6 shadow-lg lg:w-5/6">
            <div class="flex flex-row ml-auto mr-0">
                <div class="text-end">
                    <a href="" id="updateDonationBtn" data-id="{{ $donation }}" type="button" class="w-32 text-green-600 hover:text-white border-2 border-green-600 bg-green-50 hover:bg-green-600 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-600">Update</a>
                </div>
            </div>
            <div class="flex justify-between">
                <div class="text-start">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-start">{{ $donation->client[0]->first_name . " " . $donation->client[0]->last_name }}</h6>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">City:</span> {{ $donation->client[0]->city }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Email:</span> {{ $donation->client[0]->email }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Phone number:</span> {{ $donation->client[0]->phone_number }}</p>
                </div>
                <div class="text-end">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-end">Equipment type: {{ $donation->equipment[0]->equipment_type }}</h6>
                </div>
            </div>
            <p class="font-normal text-gray-700 dark:text-gray-400 w-full mt-2"><span class="font-semibold">Donating: </span></p>
            <form id="donationForm" class="mb-5" action="{{ route('donations.update', $donation) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                @error('donation')
                <p class="mt-2 text-sm text-red-600 dark:text-red-500">{{ $message }}</p>
                @enderror
                <input type="hidden" id="donation_id" value="{{old('donation_id', $donation->donation_id)}}" name="donation_id">

                <label for="donation" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"></label>
                <textarea rows="6" type="text" id="donation" name="donation" class="text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500 @error('donation') bg-red-50 border border-red-500 text-red-900 placeholder-red-700 @else bg-gray-50 border border-gray-300 text-gray-900 @enderror" placeholder="Enter donation here...">{{old('donation', $donation->donation)}}</textarea>
                <button type="submit" id="donationFormBtn" class="w-20 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-lime-600 hover:bg-lime-500 text-gray-100 rounded-lg focus:border-4 border-green-300 my-5 ml-auto mr-0 hidden">Update</button>
            </form>
        </div>
    </div>

</div>
</div>

</div>
</div>
@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    $(function() {
        let updateDonationBtn = $("#updateDonationBtn");
        let donationFormBtn = $("#donationFormBtn");

        updateDonationBtn.click(function() {
            donationFormBtn.click()
            return false;
        })

    })
</script>

Project03/resources/views/donations/index.blade.php
@extends('layouts.app')

@section('content')
<div class="flex flex-row justify-center grow bg-gray-50">
    <div class="basis-2/3 text-center">
        <h1 class="mt-10 text-2xl text-black">Donations</h1>

        <div class="relative overflow-x-auto shadow-md sm:rounded-lg p-4">
            <table id="donations" class="display w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">

                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                            First name
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                            Last Name
                        </th>
                        <th scope="col">
                            City
                        </th>
                        <th scope="col">
                            Email
                        </th>
                        <th scope="col">
                            Phone number
                        </th>
                        <th scope="col">
                            Date
                        </th>
                    </tr>
                </thead>
            </table>
        </div>

    </div>

</div>
@endsection

@section('scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.13.4/sorting/datetime-moment.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.11.5/dataRender/datetime.js"></script>

<script>
    $(document).ready(function() {
        $('#donations').DataTable({
            ajax: '/donations/allDonations',

            columns: [{
                    data: 'donation_id',
                    name: 'donation_id'
                },
                {
                    data: 'first_name',
                    name: 'first_name'
                },
                {
                    data: 'last_name',
                    name: 'last_name'
                },
                {
                    data: 'city',
                    name: 'city'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'phone_number',
                    name: 'phone_number'
                },
                {
                    data: 'donations_created_at',
                    name: 'donations_created_at',
                },
            ],
            columnDefs: [{
                targets: 0,
                data: "download_link",
                render: function(donation_id) {
                    return '<a href="donations/' + donation_id + '"><span class="font-semibold text-red-600 message" data-id="' + donation_id + '">View</span></a>';
                }
            },
            {
                targets: 6,
                render: DataTable.render.datetime('DD/MM/YYYY'),
            }]
        })
    })
</script>

@endsection

Project03/resources/views/donations/show.blade.php
@extends('layouts.app')

@section('content')
<div class="flex flex-row justify-center pb-10 grow bg-gray-50">
    <div class="basis-2/3 text-left">

        <div class="flex flex-row justify-around">
            <div class="text-start">
                <a type="button" href="{{ route('donations.index') }}" class="w-32 text-center p-1.5 pl-5 pr-5 text-sm transition-colors duration-700 transform bg-cyan-600 hover:bg-cyan-500 text-gray-100 rounded-lg focus:border-4 border-cyan-300 my-5 ml-0 mr-auto">Back</a>
            </div>
            <div class="text-start">
                <a type="button" href="{{ route('donations.edit', $donation) }}" class="w-32 text-center text-sm p-1.5 pl-5 pr-5 transition-colors duration-700 transform bg-amber-600 hover:bg-amber-500 text-gray-100 rounded-lg focus:border-4 border-amber-300 mt-5 ml-0 mr-auto">Edit</a>
            </div>
            <div class="text-start">
                <button type="button" class="w-32 text-center text-sm p-1.5 pl-5 pr-5 transition-colors duration-700 transform bg-rose-700/90 hover:bg-rose-500 text-gray-100 rounded-lg focus:border-4 border-rose-300 mt-5 ml-0 mr-auto" data-modal-target="delete-popup-modal" data-modal-toggle="delete-popup-modal">Delete</button>
            </div>
        </div>
        <h6 class="text-2xl tracking-tight text-gray-900 dark:text-white text-center mb-2">Donation:</h6>
        <div class="flex flex-col mx-auto mb-5 border rounded-lg w-full bg-gray-50 p-2 overflow-hidden overflow-y-auto p-6 shadow-lg lg:w-5/6">
            <div class="flex justify-between">
                <div class="text-start">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-start">{{ $donation->client[0]->first_name . " " . $donation->client[0]->last_name }}</h6>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">City:</span> {{ $donation->client[0]->city }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Email:</span> {{ $donation->client[0]->email }}</p>
                    <p class="font-normal text-gray-700 dark:text-gray-400 w-full"><span class="font-semibold">Phone number:</span> {{ $donation->client[0]->phone_number }}</p>
                </div>
                <div class="text-end">
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white w-full text-end">Equipment type: {{ $donation->equipment[0]->equipment_type }}</h6>
                </div>
            </div>
            <p class="font-normal text-gray-700 dark:text-gray-400 w-full mt-2"><span class="font-semibold">Donation: </span></p>

            <textarea disabled name="" id="" cols="30" rows="6" class="p-4 mt-1 mb-4 rounded-lg border-gray-300">{{ $donation->donation }}</textarea>
        </div>
    </div>

</div>
</div>

<div id="delete-popup-modal" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] md:h-full">
    <div class="relative w-full h-full max-w-md md:h-auto">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="delete-popup-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="p-6 text-center">
                <svg aria-hidden="true" class="mx-auto mb-4 text-gray-400 w-14 h-14 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to delete this donation?</h3>
                <div class="flex justify-around">
                    <form action="{{ route('donations.destroy', $donation)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" data-modal-hide="delete-popup-modal" type="button" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">
                            Yes, I'm sure
                        </button>
                    </form>
                    <button data-modal-hide="delete-popup-modal" type="button" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">No, cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
</div>
@endsection